# Generated by Django 2.2.16 on 2021-05-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100, null=True, verbose_name='輸入形体名')),
                ('shipment_per', models.TextField(blank=True, choices=[('Vessel', 'vessel'), ('DHL(Courier)', 'dhl')], null=True, verbose_name='輸入手段')),
                ('shipto_1', models.TextField(blank=True, max_length=100, null=True, verbose_name='住所1')),
                ('shipto_2', models.TextField(blank=True, max_length=100, null=True, verbose_name='住所2')),
                ('shipto_3', models.TextField(blank=True, max_length=100, null=True, verbose_name='住所3')),
                ('shipto_4', models.TextField(blank=True, max_length=100, null=True, verbose_name='住所4')),
                ('shipto_5', models.TextField(blank=True, max_length=100, null=True, verbose_name='住所5')),
                ('via', models.TextField(blank=True, choices=[('NAGOYA Port', 'nagoya'), ('OSAKA Port', 'osaka'), ('HAKATA Port', 'hakata'), ('MOJI Port', 'moji'), ('Japanese AIR Port', 'air')], max_length=50, null=True, verbose_name='経由地')),
                ('forwarder', models.TextField(blank=True, choices=[('TRADIA', 'tradia'), ('DHL', 'DHL')], max_length=50, null=True, verbose_name='フォワーダー')),
                ('trade_term', models.TextField(blank=True, choices=[('FOB Taicang', 'FOB Taicang'), ('Ex works', 'Ex Works'), ('DDP', 'DDP')], max_length=50, null=True, verbose_name='貿易条件')),
                ('payment_term', models.TextField(blank=True, choices=[('Remittance in 30 days each month', 'remittance'), ('No Coomercial Value', 'no value')], max_length=50, null=True, verbose_name='支払条件')),
                ('insurance', models.TextField(blank=True, choices=[('', ''), ('to be covered by us', 'to be covered by us')], max_length=50, null=True, verbose_name='保険')),
                ('comment', models.TextField(blank=True, max_length=100, null=True, verbose_name='備考')),
                ('nic', models.TextField(blank=True, max_length=50, null=True, verbose_name='ニックネーム')),
            ],
            options={
                'db_table': 'condition',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, max_length=100, null=True, verbose_name='コード')),
                ('name', models.TextField(blank=True, max_length=300, null=True, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='Inv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invn', models.TextField(blank=True, null=True)),
                ('etd', models.TextField(blank=True, null=True)),
                ('delivery', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inv',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Juchu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='juchu/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Po',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod', models.DateField(blank=True, null=True, verbose_name='発注日')),
                ('pon', models.TextField(blank=True, null=True, verbose_name='PO#')),
                ('per', models.TextField(blank=True, null=True, verbose_name='手段')),
                ('port', models.TextField(blank=True, null=True, verbose_name='仕向港')),
                ('shipto', models.TextField(blank=True, null=True, verbose_name='届先')),
                ('etd', models.DateField(blank=True, db_column='ETD', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('delivery', models.DateField(blank=True, null=True, verbose_name='取込日')),
                ('ft40', models.TextField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True, verbose_name='40f')),
                ('ft20', models.TextField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True, verbose_name='20f')),
                ('condition', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.Condition')),
            ],
            options={
                'db_table': 'po',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TfcCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinban', models.TextField(blank=True, max_length=100, null=True, verbose_name='品番')),
                ('item', models.TextField(blank=True, max_length=100, null=True, verbose_name='アイテム')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='詳細')),
                ('remarks', models.TextField(blank=True, max_length=100, null=True, verbose_name='備考')),
                ('unit', models.TextField(blank=True, choices=[('pcs', 'PCS'), ('set', 'SET'), ('M', 'M')], max_length=20, null=True, verbose_name='単位')),
                ('uprice', models.TextField(blank=True, max_length=40, null=True, verbose_name='単価')),
                ('ouritem', models.TextField(blank=True, null=True)),
                ('vol', models.TextField(blank=True, max_length=10, null=True, verbose_name='容積')),
                ('zaiko', models.IntegerField(blank=True, choices=[(0, '在庫管理なし'), (1, '在庫管理あり')], null=True, verbose_name='在庫管理')),
                ('kento', models.IntegerField(blank=True, choices=[(0, '発注管理なし'), (1, '発注管理あり')], null=True, verbose_name='発注管理')),
                ('hcode', models.TextField(blank=True, max_length=100, null=True, verbose_name='フクラ品番')),
                ('cat', models.TextField(blank=True, max_length=20, null=True, verbose_name='分類')),
            ],
            options={
                'db_table': 'tfc_code',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Poline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('om', models.TextField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.TfcCode')),
                ('po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.Po')),
            ],
            options={
                'db_table': 'poline',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Invline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(blank=True, null=True)),
                ('minashi', models.FloatField(blank=True, null=True)),
                ('item', models.TextField(blank=True, null=True)),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.TfcCode')),
                ('inv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.Inv')),
                ('poline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.Poline')),
            ],
            options={
                'db_table': 'invline',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinban', models.TextField(blank=True, max_length=100, null=True, verbose_name='品番')),
                ('om', models.TextField(blank=True, null=True)),
                ('juchubi', models.DateField(blank=True, null=True)),
                ('noki', models.DateField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('flag', models.TextField(blank=True, null=True)),
                ('obic', models.TextField(blank=True, max_length=100, null=True, verbose_name='オービックコード')),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.TfcCode')),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
            },
        ),
    ]
