# Generated by Django 2.2.16 on 2021-01-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invn', models.TextField(blank=True, null=True)),
                ('etd', models.TextField(blank=True, null=True)),
                ('delivery', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(blank=True, null=True)),
                ('minashi', models.FloatField(blank=True, null=True)),
                ('item', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Po',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod', models.TextField(blank=True, null=True)),
                ('pon', models.TextField(blank=True, null=True)),
                ('per', models.TextField(blank=True, null=True)),
                ('port', models.TextField(blank=True, null=True)),
                ('shipto', models.TextField(blank=True, null=True)),
                ('etd', models.TextField(blank=True, db_column='ETD', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('delivery', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'po',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('om', models.IntegerField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TfcCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinban', models.TextField(blank=True, null=True)),
                ('item', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('uprice', models.TextField(blank=True, null=True)),
                ('ouritem', models.TextField(blank=True, null=True)),
                ('vol', models.TextField(blank=True, null=True)),
                ('zaiko', models.TextField(blank=True, null=True)),
                ('kento', models.TextField(blank=True, null=True)),
                ('hcode', models.TextField(blank=True, null=True)),
                ('cat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tfc_code',
                'managed': False,
            },
        ),
    ]
