# Generated by Django 2.2.16 on 2021-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv',
            name='delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='etd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
