# Generated by Django 2.2.16 on 2021-05-24 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_auto_20210516_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='kento/')),
                ('kijunbi', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inv',
            name='delivery',
            field=models.DateField(blank=True, null=True, verbose_name='取込日'),
        ),
        migrations.AlterField(
            model_name='inv',
            name='etd',
            field=models.DateField(blank=True, null=True, verbose_name='ETD'),
        ),
        migrations.AlterField(
            model_name='inv',
            name='invn',
            field=models.TextField(blank=True, null=True, verbose_name='インボイスNo.'),
        ),
        migrations.AlterField(
            model_name='invline',
            name='inv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='po.Inv'),
        ),
    ]
