# Generated by Django 2.2.16 on 2021-01-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_juchu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinban', models.TextField(blank=True, max_length=100, null=True, verbose_name='品番')),
                ('om', models.TextField(blank=True, null=True)),
                ('juchubi', models.DateField(blank=True, null=True)),
                ('noki', models.DateField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('flag', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('obic', models.TextField(blank=True, max_length=100, null=True, verbose_name='オービックコード')),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
            },
        ),
    ]
