# Generated by Django 2.2.16 on 2021-01-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100, null=True, verbose_name='輸入形体名')),
                ('shipment_per', models.TextField(blank=True, choices=[('vessel', 'Vessel'), ('dhl', 'DHL(Courier)')], null=True, verbose_name='輸入手段')),
                ('shipto_1', models.TextField(blank=True, max_length=100, null=True, verbose_name='住所1')),
                ('shipto_2', models.TextField(blank=True, max_length=100, null=True, verbose_name='住所2')),
                ('shipto_3', models.TextField(blank=True, max_length=100, null=True, verbose_name='住所3')),
                ('shipto_4', models.TextField(blank=True, max_length=100, null=True, verbose_name='住所4')),
                ('shipto_5', models.TextField(blank=True, max_length=100, null=True, verbose_name='住所5')),
                ('via', models.TextField(blank=True, choices=[('Naogoya', 'NAGOYA Port'), ('Osaka', 'OSAKA Port'), ('Hakata', 'HAKATA Port'), ('Moji', 'MOJI Port'), ('air', 'Japanese AIR Port')], max_length=50, null=True, verbose_name='経由地')),
                ('forwarder', models.TextField(blank=True, choices=[('tradia', 'TRADIA'), ('dhl', 'DHL')], max_length=50, null=True, verbose_name='フォワーダー')),
                ('trade_term', models.TextField(blank=True, choices=[('FOB', 'FOB Taicang'), ('Ex works', 'Ex Works'), ('ddp', 'DDP')], max_length=50, null=True, verbose_name='貿易条件')),
                ('payment_term', models.TextField(blank=True, choices=[('remittance', 'Remittance in 30 days each month'), ('no value', 'No Coomercial Value')], max_length=50, null=True, verbose_name='支払条件')),
                ('insurance', models.TextField(blank=True, choices=[('', ''), ('by us', 'to be covered by us')], max_length=50, null=True, verbose_name='保険')),
                ('comment', models.TextField(blank=True, max_length=100, null=True, verbose_name='備考')),
            ],
            options={
                'db_table': 'condition',
            },
        ),
    ]
