# Generated by Django 2.2.16 on 2021-01-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0004_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='forwarder',
            field=models.TextField(blank=True, choices=[('TRADIA', 'tradia'), ('DHL', 'DHL')], max_length=50, null=True, verbose_name='フォワーダー'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='insurance',
            field=models.TextField(blank=True, choices=[('', ''), ('to be covered by us', 'to be covered by us')], max_length=50, null=True, verbose_name='保険'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='payment_term',
            field=models.TextField(blank=True, choices=[('Remittance in 30 days each month', 'remittance'), ('No Coomercial Value', 'no value')], max_length=50, null=True, verbose_name='支払条件'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='shipment_per',
            field=models.TextField(blank=True, choices=[('Vessel', 'vessel'), ('DHL(Courier)', 'dhl')], null=True, verbose_name='輸入手段'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='trade_term',
            field=models.TextField(blank=True, choices=[('FOB Taicang', 'FOB Taicang'), ('Ex works', 'Ex Works'), ('DDP', 'DDP')], max_length=50, null=True, verbose_name='貿易条件'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='via',
            field=models.TextField(blank=True, choices=[('NAGOYA Port', 'nagoya'), ('OSAKA Port', 'osaka'), ('HAKATA Port', 'hakata'), ('MOJI Port', 'moji'), ('Japanese AIR Port', 'air')], max_length=50, null=True, verbose_name='経由地'),
        ),
    ]
