# Generated by Django 2.2.16 on 2021-02-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0005_auto_20210131_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='nic',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='ニックネーム'),
        ),
    ]
