# Generated by Django 2.2.16 on 2021-05-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0005_remove_kento_kijunbi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shouhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.TextField(blank=True, null=True, verbose_name='消費月')),
                ('code', models.TextField(blank=True, null=True, verbose_name='コード')),
                ('qty', models.FloatField(blank=True, null=True, verbose_name='消費数量')),
            ],
        ),
    ]
