# Generated by Django 2.2.16 on 2021-06-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0006_shouhi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='hinmei',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='オービック商品名'),
        ),
        migrations.AddField(
            model_name='cart',
            name='kikaku',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='オービック規格'),
        ),
        migrations.AddField(
            model_name='poline',
            name='hinmei',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='オービック商品名'),
        ),
        migrations.AddField(
            model_name='poline',
            name='kikaku',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='オービック規格'),
        ),
        migrations.AddField(
            model_name='poline',
            name='ocode',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='オービック品番'),
        ),
    ]
