# Generated by Django 2.2.16 on 2021-02-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0006_condition_nic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='po',
            options={'managed': True},
        ),
    ]
