# Generated by Django 2.2.16 on 2021-02-14 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0007_auto_20210213_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='po.Condition'),
        ),
        migrations.AddField(
            model_name='po',
            name='ft20',
            field=models.TextField(blank=True, null=True, verbose_name='20f'),
        ),
        migrations.AddField(
            model_name='po',
            name='ft40',
            field=models.TextField(blank=True, null=True, verbose_name='40f'),
        ),
        migrations.AlterField(
            model_name='po',
            name='delivery',
            field=models.DateField(blank=True, null=True, verbose_name='取込日'),
        ),
        migrations.AlterField(
            model_name='po',
            name='etd',
            field=models.DateField(blank=True, db_column='ETD', null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='per',
            field=models.TextField(blank=True, null=True, verbose_name='手段'),
        ),
        migrations.AlterField(
            model_name='po',
            name='pod',
            field=models.DateField(blank=True, null=True, verbose_name='発注日'),
        ),
        migrations.AlterField(
            model_name='po',
            name='pon',
            field=models.TextField(blank=True, null=True, verbose_name='PO#'),
        ),
        migrations.AlterField(
            model_name='po',
            name='port',
            field=models.TextField(blank=True, null=True, verbose_name='仕向港'),
        ),
        migrations.AlterField(
            model_name='po',
            name='shipto',
            field=models.TextField(blank=True, null=True, verbose_name='届先'),
        ),
    ]
