# Generated by Django 2.2.16 on 2021-07-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0008_auto_20210609_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='set',
            new_name='setflag',
        ),
        migrations.RenameField(
            model_name='poline',
            old_name='set',
            new_name='setflag',
        ),
    ]
