# Generated by Django 2.2.16 on 2021-02-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0008_auto_20210214_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, max_length=100, null=True, verbose_name='コード')),
                ('name', models.TextField(blank=True, max_length=300, null=True, verbose_name='名前')),
            ],
        ),
    ]
