# Generated by Django 2.2.16 on 2021-03-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banch', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Addcover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.TextField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('invn', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banch', models.CharField(blank=True, max_length=50, null=True)),
                ('hcode', models.TextField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('kqty', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kakutei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('loc_qty', models.IntegerField(blank=True, null=True)),
                ('seisan', models.DateField(blank=True, null=True)),
                ('om', models.CharField(blank=True, max_length=50)),
                ('banch', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koshinbi', models.DateField(blank=True, null=True)),
                ('shijibi', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('loc_qty', models.IntegerField(blank=True, null=True)),
                ('seisan', models.DateField(blank=True, null=True)),
                ('om', models.CharField(blank=True, max_length=50)),
                ('banch', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seisan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('om', models.CharField(blank=True, max_length=50)),
                ('seisan', models.DateField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shiire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shiji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiji_date', models.CharField(blank=True, max_length=50)),
                ('file_name', models.FileField(upload_to='shiji/', verbose_name='ファイルを送信')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(max_length=200)),
                ('se', models.CharField(max_length=30, unique=True)),
                ('shiire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loc.Shiire')),
            ],
        ),
    ]
