# Generated by Django 2.2.16 on 2020-09-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0002_shiji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiji',
            name='seisan_shiji',
        ),
        migrations.AddField(
            model_name='shiji',
            name='shiji_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shiji',
            name='file_name',
            field=models.FileField(upload_to='shiji/'),
        ),
    ]
