# Generated by Django 2.2.16 on 2020-09-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0003_auto_20200920_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seisan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('om', models.CharField(blank=True, max_length=50)),
                ('seisan', models.DateTimeField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
