# Generated by Django 2.2.16 on 2020-09-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0004_seisan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seisan',
            name='seisan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
