# Generated by Django 2.2.16 on 2020-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0005_auto_20200921_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('seisan', models.DateField(blank=True, null=True)),
                ('om', models.CharField(blank=True, max_length=50)),
                ('banch', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
