# Generated by Django 2.2.16 on 2020-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0006_pick'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koshinbi', models.DateField(blank=True, null=True)),
                ('seizoshiji', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
