# Generated by Django 2.2.16 on 2020-09-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0007_locstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locstatus',
            name='seizoshiji',
        ),
        migrations.AddField(
            model_name='locstatus',
            name='shijibi',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
