# Generated by Django 2.2.16 on 2020-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0008_auto_20200922_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='loc_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
