# Generated by Django 2.2.16 on 2021-01-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0011_addcover_inv_invline_po_poline_tfccode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banch', models.CharField(blank=True, max_length=50, null=True)),
                ('hcode', models.TextField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('kqty', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
