# Generated by Django 2.2.16 on 2021-03-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0014_auto_20210206_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shiire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(max_length=200)),
                ('se', models.CharField(max_length=30, unique=True)),
                ('shiire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loc.Shiire')),
            ],
        ),
    ]
